# Generated by Django 6.0 on 2025-12-14 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ParkingSpot",
            fields=[
                (
                    "id",
                    models.CharField(max_length=32, primary_key=True, serialize=False),
                ),
                ("label", models.CharField(max_length=32)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Available"),
                            ("OCCUPIED", "Occupied"),
                            ("ABNORMAL", "Abnormal"),
                        ],
                        default="AVAILABLE",
                        max_length=16,
                    ),
                ),
                ("is_ev", models.BooleanField(default=False)),
                ("is_priority", models.BooleanField(default=False)),
                ("distance_raw", models.IntegerField(default=0)),
                ("floor", models.IntegerField(default=1)),
                ("section", models.CharField(default="A", max_length=8)),
                (
                    "plate_number",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                ("parked_time", models.DateTimeField(blank=True, null=True)),
                ("abnormal_reason", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="LogEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("type", models.CharField(max_length=32)),
                ("message", models.TextField()),
                (
                    "spot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.parkingspot",
                    ),
                ),
            ],
        ),
    ]
